name: 'AlliedPayment GitHub Deployment Actions'
description: 'Creates files for CD'
author:  'AlliedPayment'
branding:
  icon: 'cloud'
  color: 'purple'
inputs:
  payload:
    description: |
      JSON payload with extra information about the deployment. Default: ""
    default: ''
    required: false 
  workingdir: 
    description: working directory that the deployment repo is checked out into 
    default: ''
    required: false 
outputs:
  branch_name:
    description: The branch to create 
  deployment_name:
    description: The name of the deployment 
runs:
  using: 'docker'
  image: './Dockerfile'